#include "global.h"
#include "main.h"

#include <stdio.h>

#define STUB_FUNC(func) func { puts("function \"" #func "\" is a stub"); }
#define STUB_FUNC_QUIET(func) func {}

STUB_FUNC_QUIET(bool8 HandleLinkConnection())
STUB_FUNC_QUIET(void Task_InitUnionRoom())
STUB_FUNC(void sub_8021A28())
STUB_FUNC(void sub_8021D34())
STUB_FUNC(void sub_8022070())
STUB_FUNC(void sub_802222C())
STUB_FUNC(void sub_8022250())
STUB_FUNC(void sub_80224D0())
STUB_FUNC(void sub_8022524())
STUB_FUNC(void sub_8022554())
STUB_FUNC(void sub_8022588())
STUB_FUNC(void sub_8022600())
STUB_FUNC(void sub_80226D0())
STUB_FUNC(void sub_8022730())
STUB_FUNC(void sub_8022960())
STUB_FUNC(void sub_8022A20())
STUB_FUNC(void sub_8022A4C())
STUB_FUNC(void sub_8022A94())
STUB_FUNC(void sub_8022B28())
STUB_FUNC(void sub_8022BEC())
STUB_FUNC(void sub_8022C58())
STUB_FUNC(void sub_8022CB0())
STUB_FUNC(void sub_8022D14())
STUB_FUNC(void sub_8022E1C())
STUB_FUNC(void sub_8022E3C())
STUB_FUNC(void sub_8022E5C())
STUB_FUNC(void sub_8022EAC())
STUB_FUNC(void sub_8022F04())
STUB_FUNC(void sub_8022F1C())
STUB_FUNC(void sub_8023070())
STUB_FUNC(void sub_80231B8())
STUB_FUNC(void sub_80232EC())
STUB_FUNC(void sub_802339C())
STUB_FUNC(void sub_8023558())
STUB_FUNC(void sub_80236B8())
STUB_FUNC(void sub_802385C())
STUB_FUNC(void sub_80238F0())
STUB_FUNC(void sub_8023998())
STUB_FUNC(void sub_8023A30())
STUB_FUNC(void sub_8023BC0())
STUB_FUNC(void sub_8023CAC())
STUB_FUNC(void sub_8024048())
STUB_FUNC(void sub_8024134())
STUB_FUNC(void sub_8024228())
STUB_FUNC(void sub_80242E0())
STUB_FUNC(void sub_80243BC())
STUB_FUNC(void sub_8024444())
STUB_FUNC(void sub_8024508())
STUB_FUNC(void sub_8024568())
STUB_FUNC(void sub_8024578())
STUB_FUNC(void sub_8024604())
STUB_FUNC(void sub_8024644())
STUB_FUNC(void sub_8026988())
STUB_FUNC(void sub_8026A88())
STUB_FUNC(void sub_8026AC8())
STUB_FUNC(void sub_8026AF4())
STUB_FUNC(void sub_8026B28())
STUB_FUNC(void sub_8026B5C())
STUB_FUNC(void sub_8026BB8())
STUB_FUNC(void sub_8026C28())
STUB_FUNC(void sub_8026C50())
STUB_FUNC(void sub_8026C90())
STUB_FUNC(void sub_8026D1C())
STUB_FUNC(void sub_8026D8C())
STUB_FUNC(void sub_8026DB0())
STUB_FUNC(void sub_8026E70())
STUB_FUNC(void sub_8026EEC())
STUB_FUNC(void sub_8026F1C())
STUB_FUNC(void sub_8027234())
STUB_FUNC(void sub_80272A4())
STUB_FUNC(void sub_80272E8())
STUB_FUNC(void sub_80273F0())
STUB_FUNC(void sub_802745C())
STUB_FUNC(void sub_802749C())
STUB_FUNC(void sub_8027518())
STUB_FUNC(void sub_8027554())
STUB_FUNC(void sub_8027608())
STUB_FUNC(void sub_802762C())
STUB_FUNC(void sub_8027650())
STUB_FUNC(void sub_8027660())
STUB_FUNC(void sub_80276A0())
STUB_FUNC(void sub_80276C0())
STUB_FUNC(void sub_8027748())
STUB_FUNC(void sub_802778C())
STUB_FUNC(void sub_80277D0())
STUB_FUNC(void sub_802784C())
STUB_FUNC(void sub_802793C())
STUB_FUNC(void sub_802795C())
STUB_FUNC(void sub_80279C8())
STUB_FUNC(void sub_8027A28())
STUB_FUNC(void sub_8027A38())
STUB_FUNC(void sub_8027A48())
STUB_FUNC(void sub_8027A5C())
STUB_FUNC(void sub_8027AAC())
STUB_FUNC(void sub_8027ACC())
STUB_FUNC(void sub_8027BEC())
STUB_FUNC(void sub_8027D20())
STUB_FUNC(void sub_8027D38())
STUB_FUNC(void sub_8027DD0())
STUB_FUNC(void sub_8027DFC())
STUB_FUNC(void sub_8027E30())
STUB_FUNC(void sub_8028164())
STUB_FUNC(void sub_80282EC())
STUB_FUNC(void sub_8028318())
STUB_FUNC(void sub_8028350())
STUB_FUNC(void sub_8028374())
STUB_FUNC(void sub_80283A8())
STUB_FUNC(void sub_8028408())
STUB_FUNC(void sub_80284A8())
STUB_FUNC(void sub_80284CC())
STUB_FUNC(void sub_8028504())
STUB_FUNC(void sub_802853C())
STUB_FUNC(void sub_80285AC())
STUB_FUNC(void sub_8028614())
STUB_FUNC(void sub_8028654())
STUB_FUNC(void sub_802868C())
STUB_FUNC(void sub_80286B4())
STUB_FUNC(void nullsub_15())
STUB_FUNC(void sub_80286E4())
STUB_FUNC(void sub_8028734())
STUB_FUNC(void sub_80287E4())
STUB_FUNC(void sub_8028828())
STUB_FUNC(void sub_80288D4())
STUB_FUNC(void sub_80289E8())
STUB_FUNC(void sub_8028A34())
STUB_FUNC(void sub_8028A88())
STUB_FUNC(void sub_8028B80())
STUB_FUNC(void sub_8028BF8())
STUB_FUNC(void sub_8028C30())
STUB_FUNC(void sub_8028C7C())
STUB_FUNC(void sub_8028CA4())
STUB_FUNC(void sub_8028CD0())
STUB_FUNC(void sub_8028CF4())
STUB_FUNC(void sub_8028D44())
STUB_FUNC(void sub_8028DFC())
STUB_FUNC(void sub_8028E4C())
STUB_FUNC(void sub_8028E84())
STUB_FUNC(void sub_8028EC8())
STUB_FUNC(void sub_8028F14())
STUB_FUNC(void sub_8028FCC())
STUB_FUNC(void sub_8028FF8())
STUB_FUNC(void sub_802902C())
STUB_FUNC(void sub_802903C())
STUB_FUNC(void sub_8029074())
STUB_FUNC(void sub_8029174())
STUB_FUNC(void sub_8029274())
STUB_FUNC(void sub_80292D4())
STUB_FUNC(void sub_80292E0())
STUB_FUNC(void sub_8029314())
STUB_FUNC(void sub_8029338())
STUB_FUNC(void sub_8029440())
STUB_FUNC(void sub_80296A8())
STUB_FUNC(void sub_802988C())
STUB_FUNC(void sub_802A010())
STUB_FUNC(void sub_802A380())
STUB_FUNC(void sub_802A454())
STUB_FUNC(void sub_802A534())
STUB_FUNC(void sub_802A588())
STUB_FUNC(void unused_0())
STUB_FUNC(void nullsub_16())
STUB_FUNC(void sub_802A72C())
STUB_FUNC(void sub_802A75C())
STUB_FUNC(void sub_802A770())
STUB_FUNC(void sub_802A794())
STUB_FUNC(void sub_802A7A8())
STUB_FUNC(void sub_802A8E8())
STUB_FUNC(u16 ArcTan2(s16 x, s16 y))
STUB_FUNC(int MultiBoot(struct MultiBootParam *mp))
STUB_FUNC(void RLUnCompVram(const void *src, void *dest))
STUB_FUNC(void RLUnCompWram(const void *src, void *dest))
STUB_FUNC(void RegisterRamReset(u32 resetFlags))
STUB_FUNC(void IntrMain())
STUB_FUNC(u16 Sqrt(u32 num))
STUB_FUNC(void GameCubeMultiBoot_Hash())
STUB_FUNC_QUIET(void GameCubeMultiBoot_Main())
STUB_FUNC(void GameCubeMultiBoot_ExecuteProgram())
STUB_FUNC(void GameCubeMultiBoot_Init())
STUB_FUNC(void GameCubeMultiBoot_HandleSerialInterrupt())
STUB_FUNC(void GameCubeMultiBoot_Quit())
STUB_FUNC(void rfu_initializeAPI())
STUB_FUNC(void rfu_STC_clearAPIVariables())
STUB_FUNC(void rfu_REQ_PARENT_resumeRetransmitAndChange())
STUB_FUNC(void rfu_UNI_PARENT_getDRAC_ACK())
STUB_FUNC(void rfu_setTimerInterrupt())
STUB_FUNC(void rfu_getSTWIRecvBuffer())
STUB_FUNC(void rfu_setMSCCallback())
STUB_FUNC(void rfu_setREQCallback())
STUB_FUNC(void rfu_enableREQCallback())
STUB_FUNC(void rfu_STC_REQ_callback())
STUB_FUNC(void rfu_CB_defaultCallback())
STUB_FUNC(void rfu_waitREQComplete())
STUB_FUNC(void rfu_REQ_RFUStatus())
STUB_FUNC(void rfu_getRFUStatus())
STUB_FUNC(void sub_82E424C())
STUB_FUNC(void sub_82E425C())
STUB_FUNC(void rfu_REQ_stopMode())
STUB_FUNC(void rfu_CB_stopMode())
STUB_FUNC(void rfu_REQBN_softReset_and_checkID())
STUB_FUNC(void rfu_REQ_reset())
STUB_FUNC(void rfu_CB_reset())
STUB_FUNC(void rfu_REQ_configSystem())
STUB_FUNC(void rfu_REQ_configGameData())
STUB_FUNC(void rfu_CB_configGameData())
STUB_FUNC(void rfu_REQ_startSearchChild())
STUB_FUNC(void rfu_CB_startSearchChild())
STUB_FUNC(void rfu_STC_clearLinkStatus())
STUB_FUNC(void rfu_REQ_pollSearchChild())
STUB_FUNC(void rfu_REQ_endSearchChild())
STUB_FUNC(void rfu_CB_pollAndEndSearchChild())
STUB_FUNC(void rfu_STC_readChildList())
STUB_FUNC(void rfu_REQ_startSearchParent())
STUB_FUNC(void rfu_CB_startSearchParent())
STUB_FUNC(void rfu_REQ_pollSearchParent())
STUB_FUNC(void sub_82E4850())
STUB_FUNC(void rfu_REQ_endSearchParent())
STUB_FUNC(void rfu_STC_readParentCandidateList())
STUB_FUNC(void rfu_REQ_startConnectParent())
STUB_FUNC(void rfu_REQ_pollConnectParent())
STUB_FUNC(void rfu_CB_pollConnectParent())
STUB_FUNC(void rfu_getConnectParentStatus())
STUB_FUNC(void rfu_REQ_endConnectParent())
STUB_FUNC(void rfu_syncVBlank())
STUB_FUNC(void rfu_REQBN_watchLink())
STUB_FUNC(void rfu_STC_removeLinkData())
STUB_FUNC(void rfu_REQ_disconnect())
STUB_FUNC(void rfu_CB_disconnect())
STUB_FUNC(void rfu_REQ_CHILD_startConnectRecovery())
STUB_FUNC(void rfu_REQ_CHILD_pollConnectRecovery())
STUB_FUNC(void rfu_CB_CHILD_pollConnectRecovery())
STUB_FUNC(void rfu_CHILD_getConnectRecoveryStatus())
STUB_FUNC(void rfu_REQ_CHILD_endConnectRecovery())
STUB_FUNC(void sub_82E53F4())
STUB_FUNC(void sub_82E540A())
STUB_FUNC(void rfu_REQ_changeMasterSlave())
STUB_FUNC(void rfu_getMasterSlave())
STUB_FUNC(void rfu_clearAllSlot())
STUB_FUNC(void rfu_STC_releaseFrame())
STUB_FUNC(void rfu_clearSlot())
STUB_FUNC(void rfu_setRecvBuffer())
STUB_FUNC(void rfu_NI_setSendData())
STUB_FUNC(void rfu_UNI_setSendData())
STUB_FUNC(void rfu_NI_CHILD_setSendGameName())
STUB_FUNC(void rfu_STC_setSendData_org())
STUB_FUNC(void rfu_changeSendTarget())
STUB_FUNC(void rfu_NI_stopReceivingData())
STUB_FUNC(void rfu_UNI_changeAndReadySendData())
STUB_FUNC(void rfu_UNI_readySendData())
STUB_FUNC(void rfu_UNI_clearRecvNewDataFlag())
STUB_FUNC(void rfu_REQ_sendData())
STUB_FUNC(void rfu_CB_sendData())
STUB_FUNC(void rfu_CB_sendData2())
STUB_FUNC(void sub_82E5F00())
STUB_FUNC(void rfu_constructSendLLFrame())
STUB_FUNC(void rfu_STC_NI_constructLLSF())
STUB_FUNC(void rfu_STC_UNI_constructLLSF())
STUB_FUNC(void rfu_REQ_recvData())
STUB_FUNC(void rfu_CB_recvData())
STUB_FUNC(void rfu_STC_PARENT_analyzeRecvPacket())
STUB_FUNC(void rfu_STC_CHILD_analyzeRecvPacket())
STUB_FUNC(void rfu_STC_analyzeLLSF())
STUB_FUNC(void rfu_STC_UNI_receive())
STUB_FUNC(void rfu_STC_NI_receive_Sender())
STUB_FUNC(void rfu_STC_NI_receive_Receiver())
STUB_FUNC(void rfu_STC_NI_initSlot_asRecvControllData())
STUB_FUNC(void rfu_STC_NI_initSlot_asRecvDataEntity())
STUB_FUNC(void rfu_NI_checkCommFailCounter())
STUB_FUNC(void rfu_REQ_noise())
STUB_FUNC(void sub_82E6D6C())
STUB_FUNC(void sub_82E6E20())
STUB_FUNC(void sub_82E6E94())
STUB_FUNC(void sub_82E6F88())
STUB_FUNC(void sub_82E6FA2())
STUB_FUNC(void umul3232H32())
STUB_FUNC_QUIET(void SoundMain())
STUB_FUNC(void SoundMainRAM())
STUB_FUNC(void SoundMainBTM())
STUB_FUNC(void RealClearChain())
STUB_FUNC(void ply_fine())
STUB_FUNC(void MPlayJumpTableCopy())
STUB_FUNC(void ply_goto())
STUB_FUNC(void ply_patt())
STUB_FUNC(void ply_pend())
STUB_FUNC(void ply_rept())
STUB_FUNC(void ply_prio())
STUB_FUNC(void ply_tempo())
STUB_FUNC(void ply_keysh())
STUB_FUNC(void ply_voice())
STUB_FUNC(void ply_vol())
STUB_FUNC(void ply_pan())
STUB_FUNC(void ply_bend())
STUB_FUNC(void ply_bendr())
STUB_FUNC(void ply_lfodl())
STUB_FUNC(void ply_modt())
STUB_FUNC(void ply_tune())
STUB_FUNC(void ply_port())
STUB_FUNC(void m4aSoundVSync())
STUB_FUNC(void MPlayMain())
STUB_FUNC(void TrackStop())
STUB_FUNC(void ChnVolSetAsm())
STUB_FUNC(void ply_note())
STUB_FUNC(void ply_endtie())
STUB_FUNC(void clear_modM())
STUB_FUNC(void ld_r3_tp_adr_i())
STUB_FUNC(void ply_lfos())
STUB_FUNC(void ply_mod())
STUB_FUNC(void sub_802DA44())
STUB_FUNC(void sub_802DA8C())
STUB_FUNC(void sub_802DA9C())
STUB_FUNC(void sub_802DB18())
STUB_FUNC(void sub_802DB8C())
STUB_FUNC(void sub_802DBF8())
STUB_FUNC(void sub_802DC80())
STUB_FUNC(void sub_802DC9C())
STUB_FUNC(void sub_802DCCC())
STUB_FUNC(void sub_802DD08())
STUB_FUNC(void sub_802DD64())
STUB_FUNC(void sub_802DD74())
STUB_FUNC(void sub_802DD88())
STUB_FUNC(void sub_802DDA0())
STUB_FUNC(void sub_802DDB8())
STUB_FUNC(void sub_802DDCC())
STUB_FUNC(void sub_802DDE0())
STUB_FUNC(void sub_802DDF4())
STUB_FUNC(void sub_802DE08())
STUB_FUNC(void sub_802DE1C())
STUB_FUNC(void sub_802DED8())
STUB_FUNC(void sub_802DF70())
STUB_FUNC(void sub_802DFD4())
STUB_FUNC(void sub_802E00C())
STUB_FUNC(void sub_802E058())
STUB_FUNC(void sub_802E090())
STUB_FUNC(void sub_802E0AC())
STUB_FUNC(void sub_802E0D0())
STUB_FUNC(void sub_802E120())
STUB_FUNC(void sub_802E138())
STUB_FUNC(void sub_802E1BC())
STUB_FUNC(void sub_802E234())
STUB_FUNC(void sub_802E264())
STUB_FUNC(void sub_802E2D0())
STUB_FUNC(void sub_802E32C())
STUB_FUNC(void ResetPokeJumpResults())
STUB_FUNC(void sub_802E354())
STUB_FUNC(void sub_802E3A8())
STUB_FUNC(void sub_802E3C4())
STUB_FUNC(void sub_802E3E4())
STUB_FUNC(void sub_802E500())
STUB_FUNC(void sub_802E620())
STUB_FUNC(void sub_802E63C())
STUB_FUNC(void sub_802E688())
STUB_FUNC(void sub_802E6BC())
STUB_FUNC(void sub_802E6D0())
STUB_FUNC(void sub_802E75C())
STUB_FUNC(void sub_802E83C())
STUB_FUNC(void sub_802E8C8())
STUB_FUNC(void sub_802E938())
STUB_FUNC(void sub_802EA50())
STUB_FUNC(void sub_802EAB0())
STUB_FUNC(void sub_802EB24())
STUB_FUNC(void sub_802EB84())
STUB_FUNC(void sub_802EB98())
STUB_FUNC(void sub_802EC98())
STUB_FUNC(void sub_802EDCC())
STUB_FUNC(void sub_802EE30())
STUB_FUNC(void sub_802EE5C())
STUB_FUNC(void sub_802EF50())
STUB_FUNC(void sub_802EFA8())
STUB_FUNC(void sub_802EFFC())
STUB_FUNC(void sub_81D0450())
STUB_FUNC(void sub_81D04A0())
STUB_FUNC(void sub_81D04B8())
STUB_FUNC(void sub_81D04C4())
STUB_FUNC(void sub_81D0548())
STUB_FUNC(void sub_81D05D4())
STUB_FUNC(void sub_81D05DC())
STUB_FUNC(void sub_81D061C())
STUB_FUNC(void sub_81D0664())
STUB_FUNC(void sub_81D0688())
STUB_FUNC(void sub_81D06C4())
STUB_FUNC(void sub_81D06D4())
STUB_FUNC(void sub_81D06E4())
STUB_FUNC(void sub_81D0760())
STUB_FUNC(void sub_81D07D8())
STUB_FUNC(void sub_81D0814())
STUB_FUNC(void sub_81D0914())
STUB_FUNC(void sub_81D092C())
STUB_FUNC(void sub_81D0944())
STUB_FUNC(void sub_81D0954())
STUB_FUNC(void sub_81D0978())
STUB_FUNC(void sub_81D09B0())
STUB_FUNC(void sub_81D09E0())
STUB_FUNC(void sub_81D09F4())
STUB_FUNC(void sub_81D0A58())
STUB_FUNC(void sub_81D0A6C())
STUB_FUNC(void sub_81D0C54())
STUB_FUNC(void sub_81D0C84())
STUB_FUNC(void sub_81D0D2C())
STUB_FUNC(void sub_81D0D8C())
STUB_FUNC(void sub_81D0E00())
STUB_FUNC(void sub_81C9924())
STUB_FUNC(void sub_81C9940())
STUB_FUNC(void sub_81C9958())
STUB_FUNC(void sub_81C9990())
STUB_FUNC(void sub_81C99C0())
STUB_FUNC(void sub_81C99D4())
STUB_FUNC(void sub_81C99FC())
STUB_FUNC(void sub_81C9A10())
STUB_FUNC(void sub_81C9C6C())
STUB_FUNC(void sub_81C9CA8())
STUB_FUNC(void sub_81C9D44())
STUB_FUNC(void sub_81C9DD8())
STUB_FUNC(void sub_81C9E58())
STUB_FUNC(void sub_81C9EC8())
STUB_FUNC(void sub_81C9EF8())
STUB_FUNC(void sub_81C9F28())
STUB_FUNC(void sub_81C9FC4())
STUB_FUNC(void sub_81C9FEC())
STUB_FUNC(void sub_81CA02C())
STUB_FUNC(void sub_81CA094())
STUB_FUNC(void sub_81CA0C8())
STUB_FUNC(void sub_81CA0EC())
STUB_FUNC(void sub_81CA20C())
STUB_FUNC(void sub_81CA278())
STUB_FUNC(void sub_81CA2DC())
STUB_FUNC(void sub_81CA324())
STUB_FUNC(void sub_81CA35C())
STUB_FUNC(void sub_81CA3B4())
STUB_FUNC(void sub_81CA448())
STUB_FUNC(void sub_81CA474())
STUB_FUNC(void sub_81CA4AC())
STUB_FUNC(void sub_81CA580())
STUB_FUNC(void sub_81CA640())
STUB_FUNC(void sub_81CA698())
STUB_FUNC(void sub_81CA6AC())
STUB_FUNC(void sub_81CA6E0())
STUB_FUNC(void sub_81CA714())
STUB_FUNC(void sub_81CA770())
STUB_FUNC(void sub_81CA7C4())
STUB_FUNC(void sub_81CA7D4())
STUB_FUNC(void sub_81CA7F4())
STUB_FUNC(void sub_81CA808())
STUB_FUNC(void sub_81CA818())
STUB_FUNC(void sub_81CA850())
STUB_FUNC(void sub_81CA864())
STUB_FUNC(void sub_81CA89C())
STUB_FUNC(void sub_81CA8B0())
STUB_FUNC(void sub_81CA914())
STUB_FUNC(void titlescreen_0())
STUB_FUNC(void sub_81CA994())
STUB_FUNC(void sub_81CA9C8())
STUB_FUNC(void sub_81CA9D8())
STUB_FUNC(void sub_81CA9EC())
STUB_FUNC(void sub_81CAA3C())
STUB_FUNC(void sub_81CAADC())
STUB_FUNC(void sub_81CCFD8())
STUB_FUNC(void sub_81CD024())
STUB_FUNC(void sub_81CD070())
STUB_FUNC(void sub_81CD08C())
STUB_FUNC(void sub_81CD110())
STUB_FUNC(void sub_81CD19C())
STUB_FUNC(void sub_81CD1C0())
STUB_FUNC(void sub_81CD1E4())
STUB_FUNC(void sub_81CD258())
STUB_FUNC(void sub_81CD3C4())
STUB_FUNC(void sub_81CD548())
STUB_FUNC(void sub_81CD5CC())
STUB_FUNC(void sub_81CD624())
STUB_FUNC(void sub_81CD824())
STUB_FUNC(void sub_81CD970())
STUB_FUNC(void sub_81CD9F8())
STUB_FUNC(void sub_81CDA1C())
STUB_FUNC(void sub_81CDB98())
STUB_FUNC(void sub_81CDC50())
STUB_FUNC(void sub_81CDC60())
STUB_FUNC(void sub_81CDC70())
STUB_FUNC(void sub_81CDC84())
STUB_FUNC(void sub_81CDC9C())
STUB_FUNC(void sub_81CDCB4())
STUB_FUNC(void sub_81CDCD4())
STUB_FUNC(void sub_81CDCEC())
STUB_FUNC(void sub_81CDD04())
STUB_FUNC(void sub_81CDD24())
STUB_FUNC(void sub_81CDD48())
STUB_FUNC(void sub_81CDD5C())
STUB_FUNC(void sub_81CDD7C())
STUB_FUNC(void sub_81CDDB0())
STUB_FUNC(void sub_81CDDD4())
STUB_FUNC(void sub_81CDE2C())
STUB_FUNC(void sub_81CDE64())
STUB_FUNC(void sub_81CDE80())
STUB_FUNC(void sub_81CDE94())
STUB_FUNC(void sub_81CE2D0())
STUB_FUNC(void sub_81CE37C())
STUB_FUNC(void sub_81CE4D8())
STUB_FUNC(void sub_81CE5E4())
STUB_FUNC(void sub_81CE6BC())
STUB_FUNC(void sub_81CE700())
STUB_FUNC(void sub_81CE738())
STUB_FUNC(void sub_81CE754())
STUB_FUNC(void sub_81CE934())
STUB_FUNC(void sub_81CE964())
STUB_FUNC(void sub_81CE990())
STUB_FUNC(void sub_81CE9C8())
STUB_FUNC(void sub_81CE9E4())
STUB_FUNC(void sub_81CEBF4())
STUB_FUNC(void sub_81CECA0())
STUB_FUNC(void sub_81CED10())
STUB_FUNC(void sub_81CED30())
STUB_FUNC(void sub_81CEE44())
STUB_FUNC(void sub_81CEE68())
STUB_FUNC(void sub_81CEE74())
STUB_FUNC(void sub_81CEE90())
STUB_FUNC(void sub_81CEEC8())
STUB_FUNC(void sub_81CEF14())
STUB_FUNC(void sub_81CEF3C())
STUB_FUNC(void sub_81CEF98())
STUB_FUNC(void sub_81CEFDC())
STUB_FUNC(void sub_81CEFF0())
STUB_FUNC(void sub_81CF010())
STUB_FUNC(void sub_81CF030())
STUB_FUNC(void sub_81CF0B0())
STUB_FUNC(void sub_81CF0B8())
STUB_FUNC(void sub_81CF0C0())
STUB_FUNC(void sub_81CF0D0())
STUB_FUNC(void sub_81CF0E0())
STUB_FUNC(void sub_81CF0F0())
STUB_FUNC(void sub_81CF10C())
STUB_FUNC(void sub_81CF11C())
STUB_FUNC(void sub_81CF134())
STUB_FUNC(void sub_81CF1C4())
STUB_FUNC(void sub_81CF1D8())
STUB_FUNC(void sub_81CF278())
STUB_FUNC(void sub_81CF2C4())
STUB_FUNC(void sub_81CF330())
STUB_FUNC(void sub_81CF368())
STUB_FUNC(void sub_81CF3A0())
STUB_FUNC(void sub_81CF3D0())
STUB_FUNC(void sub_81CF3E4())
STUB_FUNC(void sub_81CF3F8())
STUB_FUNC(void sub_81CF418())
STUB_FUNC(void sub_81CF578())
STUB_FUNC(void sub_81CF5F0())
STUB_FUNC(void sub_81CF668())
STUB_FUNC(void sub_81CF6E0())
STUB_FUNC(void sub_81CF758())
STUB_FUNC(void sub_81CF798())
STUB_FUNC(void sub_81CF7C8())
STUB_FUNC(void sub_81CF7F4())
STUB_FUNC(void sub_81CF88C())
STUB_FUNC(void sub_81CF8E4())
STUB_FUNC(void sub_81CF9BC())
STUB_FUNC(void sub_81CFA04())
STUB_FUNC(void sub_81CFA34())
STUB_FUNC(void sub_81CFA48())
STUB_FUNC(void sub_81CFA68())
STUB_FUNC(void sub_81CFA88())
STUB_FUNC(void sub_81CFB08())
STUB_FUNC(void sub_81CFB10())
STUB_FUNC(void sub_81CFB18())
STUB_FUNC(void sub_81CFB28())
STUB_FUNC(void sub_81CFB38())
STUB_FUNC(void sub_81CFB48())
STUB_FUNC(void sub_81CFB64())
STUB_FUNC(void sub_81CFB74())
STUB_FUNC(void sub_81CFB8C())
STUB_FUNC(void sub_81CFC2C())
STUB_FUNC(void sub_81CFC40())
STUB_FUNC(void sub_81CFCEC())
STUB_FUNC(void sub_81CFD58())
STUB_FUNC(void sub_81CFDD0())
STUB_FUNC(void sub_81CFE08())
STUB_FUNC(void sub_81CFE40())
STUB_FUNC(void sub_81CFE70())
STUB_FUNC(void sub_81CFE84())
STUB_FUNC(void sub_81CFE98())
STUB_FUNC(void sub_81CFEB8())
STUB_FUNC(void sub_81CFFFC())
STUB_FUNC(void sub_81D0074())
STUB_FUNC(void sub_81D00EC())
STUB_FUNC(void sub_81D0164())
STUB_FUNC(void sub_81D01DC())
STUB_FUNC(void sub_81D021C())
STUB_FUNC(void sub_81D024C())
STUB_FUNC(void sub_81D0288())
STUB_FUNC(void sub_81D02B0())
STUB_FUNC(void sub_81D0304())
STUB_FUNC(void sub_81D035C())
STUB_FUNC(u32 MidiKeyToFreq(struct WaveData *wav, u8 key, u8 fineAdjust))
STUB_FUNC(void UnusedDummyFunc(void))
STUB_FUNC(void MPlayContinue(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void MPlayFadeOut(struct MusicPlayerInfo *mplayInfo, u16 speed))
STUB_FUNC(void m4aSoundInit(void))
STUB_FUNC_QUIET(void m4aSoundMain(void))
STUB_FUNC(void m4aSongNumStart(u16 n))
STUB_FUNC(void m4aSongNumStartOrChange(u16 n))
STUB_FUNC(void m4aSongNumStartOrContinue(u16 n))
STUB_FUNC(void m4aSongNumStop(u16 n))
STUB_FUNC(void m4aSongNumContinue(u16 n))
STUB_FUNC(void m4aMPlayAllStop(void))
STUB_FUNC(void m4aMPlayContinue(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void m4aMPlayAllContinue(void))
STUB_FUNC(void m4aMPlayFadeOut(struct MusicPlayerInfo *mplayInfo, u16 speed))
STUB_FUNC(void m4aMPlayFadeOutTemporarily(struct MusicPlayerInfo *mplayInfo, u16 speed))
STUB_FUNC(void m4aMPlayFadeIn(struct MusicPlayerInfo *mplayInfo, u16 speed))
STUB_FUNC(void m4aMPlayImmInit(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void MPlayExtender(struct CgbChannel *cgbChans))
STUB_FUNC(void MusicPlayerJumpTableCopy(void))
STUB_FUNC(void ClearChain(void *x))
STUB_FUNC(void Clear64byte(void *x))
STUB_FUNC(void SoundInit(struct SoundInfo *soundInfo))
STUB_FUNC(void SampleFreqSet(u32 freq))
STUB_FUNC(void m4aSoundMode(u32 mode))
STUB_FUNC(void SoundClear(void))
STUB_FUNC(void m4aSoundVSyncOff(void))
STUB_FUNC(void m4aSoundVSyncOn(void))
STUB_FUNC(void MPlayOpen(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *tracks, u8 trackCount))
STUB_FUNC(void MPlayStart(struct MusicPlayerInfo *mplayInfo, struct SongHeader *songHeader))
STUB_FUNC(void m4aMPlayStop(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void FadeOutBody(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void TrkVolPitSet(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(u32 MidiKeyToCgbFreq(u8 chanNum, u8 key, u8 fineAdjust))
STUB_FUNC(void CgbOscOff(u8 chanNum))
STUB_FUNC(void CgbModVol(struct CgbChannel *chan))
STUB_FUNC(void CgbSound(void))
STUB_FUNC(void m4aMPlayTempoControl(struct MusicPlayerInfo *mplayInfo, u16 tempo))
STUB_FUNC(void m4aMPlayVolumeControl(struct MusicPlayerInfo *mplayInfo, u16 trackBits, u16 volume))
STUB_FUNC(void m4aMPlayPitchControl(struct MusicPlayerInfo *mplayInfo, u16 trackBits, s16 pitch))
STUB_FUNC(void m4aMPlayPanpotControl(struct MusicPlayerInfo *mplayInfo, u16 trackBits, s8 pan))
STUB_FUNC(void ClearModM(struct MusicPlayerTrack *track))
STUB_FUNC(void m4aMPlayModDepthSet(struct MusicPlayerInfo *mplayInfo, u16 trackBits, u8 modDepth))
STUB_FUNC(void m4aMPlayLFOSpeedSet(struct MusicPlayerInfo *mplayInfo, u16 trackBits, u8 lfoSpeed))
STUB_FUNC(void ply_memacc(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xcmd(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xxx(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xwave(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xtype(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xatta(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xdeca(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xsust(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xrele(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xiecv(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xiecl(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xleng(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xswee(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xcmd_0C(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void ply_xcmd_0D(struct MusicPlayerInfo *mplayInfo, struct MusicPlayerTrack *track))
STUB_FUNC(void DummyFunc(void))
STUB_FUNC(struct MusicPlayerInfo *SetPokemonCryTone(struct ToneData *tone))
STUB_FUNC(void SetPokemonCryVolume(u8 val))
STUB_FUNC(void SetPokemonCryPanpot(s8 val))
STUB_FUNC(void SetPokemonCryPitch(s16 val))
STUB_FUNC(void SetPokemonCryLength(u16 val))
STUB_FUNC(void SetPokemonCryRelease(u8 val))
STUB_FUNC(void SetPokemonCryProgress(u32 val))
STUB_FUNC(void SetPokemonCryChorus(s8 val))
STUB_FUNC(void SetPokemonCryStereo(u32 val))
STUB_FUNC(void SetPokemonCryPriority(u8 val))
STUB_FUNC(void IsPokemonCryPlaying(struct MusicPlayerInfo *mplayInfo))
STUB_FUNC(void MultiBootInit(struct MultiBootParam *mp))
STUB_FUNC(int MultiBootMain(struct MultiBootParam *mp))
STUB_FUNC(void MultiBootStartProbe(struct MultiBootParam *mp))
STUB_FUNC(void MultiBootStartMaster(struct MultiBootParam *mp, const u8 *srcp, int length, u8 palette_color, s8 palette_speed))
STUB_FUNC(int MultiBootCheckComplete(struct MultiBootParam *mp))
STUB_FUNC(IntrFunc IntrSIO32(void))
